services:
  - type: web
    name: ukoo-app
    env: php
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_USER
        value: your-db-user
      - key: DB_PASS
        value: your-db-password
      - key: DB_NAME
        value: ukoo
      - key: DB_PORT
        value: 3306
